### ISSUE TITLE
Edgar Axel Sandoval Hernández 

### ISSUE THREAD

**Issue by EdgarExa** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-EdgarExa#1]
[cuadro comparativo_083008.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-EdgarExa/files/9509351/cuadro.comparativo_083008.pdf)
Edgar Axel Sandoval Hernández

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica tiene un 15%

**Comment by josealfredo79** [comment]
Revisado...
